import type { Currency } from '@packages/general-codes/src/types'

const currencies = [
  // 🔹 FIAT Currencies
  {
    code: 'CZK',
    symbol: 'Kč',
    symbolBefore: false,
    name: 'Czech Koruna',
    providers: [
      'CNB',
      'currencyLayer',
      'trademade-live',
      'trademade-convert',
      'currencyCloud',
    ],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'EUR',
    symbol: '€',
    symbolBefore: false,
    name: 'Euro',
    providers: [
      'currencyLayer',
      'trademade-live',
      'trademade-convert',
      'currencyCloud',
    ],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'USD',
    symbol: '$',
    symbolBefore: true,
    name: 'United States Dollar',
    providers: [
      'currencyLayer',
      'trademade-live',
      'trademade-convert',
      'currencyCloud',
    ],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'PLN',
    symbol: 'zł',
    symbolBefore: false,
    name: 'Polish Złoty',
    providers: [
      'currencyLayer',
      'trademade-live',
      'trademade-convert',
      'currencyCloud',
    ],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'RON',
    symbol: 'lei',
    symbolBefore: false,
    name: 'Romanian Leu',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'GBP',
    symbol: '£',
    symbolBefore: true,
    name: 'British Pound Sterling',
    providers: [
      'currencyLayer',
      'trademade-live',
      'trademade-convert',
      'CNB',
      'currencyCloud',
    ],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'RUB',
    symbol: '₽',
    symbolBefore: false,
    name: 'Russian Ruble',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'HUF',
    symbol: 'Ft',
    symbolBefore: false,
    name: 'Hungarian Forint',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'CHF',
    symbol: 'SFr.',
    symbolBefore: true,
    name: 'Swiss Franc',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'DKK',
    symbol: 'kr',
    symbolBefore: false,
    name: 'Danish Krone',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'SEK',
    symbol: 'kr',
    symbolBefore: false,
    name: 'Swedish Krona',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'HRK',
    symbol: 'kn',
    symbolBefore: false,
    name: 'Croatian Kuna',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'NOK',
    symbol: 'kr',
    symbolBefore: false,
    name: 'Norwegian Krone',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'BGN',
    symbol: 'лв',
    symbolBefore: false,
    name: 'Bulgarian Lev',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'TRY',
    symbol: '₺',
    symbolBefore: false,
    name: 'Turkish Lira',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'AUD',
    symbol: '$',
    symbolBefore: true,
    name: 'Australian Dollar',
    providers: [
      'currencyLayer',
      'trademade-live',
      'trademade-convert',
      'CNB',
      'currencyCloud',
    ],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'CAD',
    symbol: '$',
    symbolBefore: true,
    name: 'Canadian Dollar',
    providers: [
      'currencyLayer',
      'trademade-live',
      'trademade-convert',
      'CNB',
      'currencyCloud',
    ],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'JPY',
    symbol: '¥',
    symbolBefore: true,
    name: 'Japanese Yen',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 0,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'CNY',
    symbol: '¥',
    symbolBefore: true,
    name: 'Chinese Yuan',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'INR',
    symbol: '₹',
    symbolBefore: true,
    name: 'Indian Rupee',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'BRL',
    symbol: 'R$',
    symbolBefore: true,
    name: 'Brazilian Real',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'MXN',
    symbol: '$',
    symbolBefore: true,
    name: 'Mexican Peso',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'ZAR',
    symbol: 'R',
    symbolBefore: true,
    name: 'South African Rand',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'SGD',
    symbol: '$',
    symbolBefore: true,
    name: 'Singapore Dollar',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'HKD',
    symbol: '$',
    symbolBefore: true,
    name: 'Hong Kong Dollar',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'KRW',
    symbol: '₩',
    symbolBefore: true,
    name: 'South Korean Won',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 0,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'MYR',
    symbol: 'RM',
    symbolBefore: true,
    name: 'Malaysian Ringgit',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'THB',
    symbol: '฿',
    symbolBefore: true,
    name: 'Thai Baht',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'IDR',
    symbol: 'Rp',
    symbolBefore: true,
    name: 'Indonesian Rupiah',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'PHP',
    symbol: '₱',
    symbolBefore: true,
    name: 'Philippine Peso',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'AED',
    symbol: 'د.إ',
    symbolBefore: false,
    name: 'UAE Dirham',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'SAR',
    symbol: '﷼',
    symbolBefore: false,
    name: 'Saudi Riyal',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'ILS',
    symbol: '₪',
    symbolBefore: true,
    name: 'Israeli New Shekel',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'EGP',
    symbol: '£',
    symbolBefore: true,
    name: 'Egyptian Pound',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'NGN',
    symbol: '₦',
    symbolBefore: true,
    name: 'Nigerian Naira',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'PKR',
    symbol: '₨',
    symbolBefore: true,
    name: 'Pakistani Rupee',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'COP',
    symbol: '$',
    symbolBefore: true,
    name: 'Colombian Peso',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'CLP',
    symbol: '$',
    symbolBefore: true,
    name: 'Chilean Peso',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 0,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'PEN',
    symbol: 'S/',
    symbolBefore: true,
    name: 'Peruvian Sol',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'VND',
    symbol: '₫',
    symbolBefore: false,
    name: 'Vietnamese Dong',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 0,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'KZT',
    symbol: '₸',
    symbolBefore: false,
    name: 'Kazakhstani Tenge',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },
  {
    code: 'UAH',
    symbol: '₴',
    symbolBefore: false,
    name: 'Ukrainian Hryvnia',
    providers: ['currencyLayer', 'trademade-live', 'trademade-convert', 'CNB'],
    decimals: 2,
    networks: null,
    type: 'FIAT',
  },

  // 🔹 Crypto Currencies
  {
    code: 'BTC',
    symbol: '₿',
    symbolBefore: true,
    name: 'Bitcoin',
    providers: ['kraken', 'binance'],
    decimals: 8,
    networks: ['BTC'],
    type: 'CRYPTO',
  },
  {
    code: 'ETH',
    symbol: 'Ξ',
    symbolBefore: true,
    name: 'Ethereum',
    providers: ['kraken', 'binance'],
    decimals: 18,
    networks: ['ETH', 'ARBITRUM', 'OPTIMISM', 'POLYGON'],
    type: 'CRYPTO',
  },
  {
    code: 'ADA',
    symbol: '₳',
    symbolBefore: true,
    name: 'Cardano',
    providers: ['kraken', 'binance'],
    decimals: 6,
    networks: ['CARDANO'],
    type: 'CRYPTO',
  },
  {
    code: 'DOT',
    symbol: '◎',
    symbolBefore: true,
    name: 'Polkadot',
    providers: ['kraken', 'binance'],
    decimals: 10,
    networks: ['POLKADOT'],
    type: 'CRYPTO',
  },
  {
    code: 'ATOM',
    symbol: '⚛',
    symbolBefore: true,
    name: 'Cosmos',
    providers: ['kraken', 'binance'],
    decimals: 6,
    networks: ['COSMOS'],
    type: 'CRYPTO',
  },
  {
    code: 'XRP',
    symbol: 'Ʀ',
    symbolBefore: true,
    name: 'Ripple',
    providers: ['kraken', 'binance'],
    decimals: 6,
    networks: ['XRP'],
    type: 'CRYPTO',
  },
  {
    code: 'LTC',
    symbol: 'Ł',
    symbolBefore: true,
    name: 'Litecoin',
    providers: ['kraken', 'binance'],
    decimals: 8,
    networks: ['LTC'],
    type: 'CRYPTO',
  },
  {
    code: 'SOL',
    symbol: '◎',
    symbolBefore: true,
    name: 'Solana',
    providers: ['kraken', 'binance'],
    decimals: 9,
    networks: ['SOLANA'],
    type: 'CRYPTO',
  },
  {
    code: 'DOGE',
    symbol: 'Ð',
    symbolBefore: true,
    name: 'Dogecoin',
    providers: ['kraken', 'binance'],
    decimals: 8,
    networks: ['DOGE'],
    type: 'CRYPTO',
  },
  {
    code: 'MATIC',
    symbol: 'M',
    symbolBefore: true,
    name: 'Polygon',
    providers: ['kraken', 'binance'],
    decimals: 18,
    networks: ['ETH', 'POLYGON'],
    type: 'CRYPTO',
  },
  {
    code: 'AVAX',
    symbol: '⛰',
    symbolBefore: true,
    name: 'Avalanche',
    providers: ['kraken', 'binance'],
    decimals: 18,
    networks: ['AVALANCHE'],
    type: 'CRYPTO',
  },
] as const satisfies readonly Currency[]

export default currencies

export type CurrencyCode = (typeof currencies)[number]['code']
export type CurrencyType = (typeof currencies)[number]['type']
