import type { Bank } from '../types'

const banks = [
  {
    name: 'Komerční banka, a.s.',
    shortName: 'KB',
    code: '0100',
    country: 'Czechia',
  },
  {
    name: 'Československá obchodní banka, a. s.',
    shortName: 'ČSOB',
    code: '0300',
    country: 'Czechia',
  },
  {
    name: 'MONETA Money Bank, a.s.',
    shortName: 'MONETA',
    code: '0600',
    country: 'Czechia',
  },
  {
    name: 'ČESKÁ NÁRODNÍ BANKA',
    shortName: 'ČNB',
    code: '0710',
    country: 'Czechia',
  },
  {
    name: 'Česká spořitelna, a.s.',
    shortName: 'ČS',
    code: '0800',
    country: 'Czechia',
  },
  {
    name: 'Fio banka, a.s.',
    shortName: 'Fio',
    code: '2010',
    country: 'Czechia',
  },
  {
    name: 'Citfin, spořitelní družstvo',
    shortName: 'Citfin',
    code: '2060',
    country: 'Czechia',
  },
  {
    name: 'TRINITY BANK a.s.',
    shortName: 'Trinity',
    code: '2070',
    country: 'Czechia',
  },
  {
    name: 'ČSOB Hypoteční banka, a.s.',
    shortName: 'ČSOB Hypo',
    code: '2100',
    country: 'Czechia',
  },
  {
    name: 'Peněžní dům, spořitelní družstvo',
    shortName: 'Peněžní dům',
    code: '2200',
    country: 'Czechia',
  },
  {
    name: 'Artesa, spořitelní družstvo',
    shortName: 'Artesa',
    code: '2220',
    country: 'Czechia',
  },
  {
    name: 'Banka CREDITAS a.s.',
    shortName: 'Creditas',
    code: '2250',
    country: 'Czechia',
  },
  {
    name: 'NEY spořitelní družstvo',
    shortName: 'NEY',
    code: '2260',
    country: 'Czechia',
  },
  {
    name: 'Citibank Europe plc, organizační složka',
    shortName: 'Citibank',
    code: '2600',
    country: 'Czechia',
  },
  {
    name: 'UniCredit Bank Czech Republic and Slovakia, a.s.',
    shortName: 'UniCredit',
    code: '2700',
    country: 'Czechia',
  },
  {
    name: 'Air Bank a.s.',
    shortName: 'Air Bank',
    code: '3030',
    country: 'Czechia',
  },
  {
    name: 'PKO BP S.A., Czech Branch',
    shortName: 'PKO BP',
    code: '3060',
    country: 'Czechia',
  },
  {
    name: 'ING Bank N.V.',
    shortName: 'ING',
    code: '3500',
    country: 'Czechia',
  },
  {
    name: 'Národní rozvojová banka, a.s.',
    shortName: 'NRB',
    code: '4300',
    country: 'Czechia',
  },
  {
    name: 'Raiffeisenbank a.s.',
    shortName: 'Raiffeisen',
    code: '5500',
    country: 'Czechia',
  },
  {
    name: 'J&T BANKA, a.s.',
    shortName: 'J&T',
    code: '5800',
    country: 'Czechia',
  },
  {
    name: 'PPF banka a.s.',
    shortName: 'PPF',
    code: '6000',
    country: 'Czechia',
  },
  {
    name: 'COMMERZBANK Aktiengesellschaft, pobočka Praha',
    shortName: 'Commerzbank',
    code: '6200',
    country: 'Czechia',
  },
  {
    name: 'mBank S.A., organizační složka',
    shortName: 'mBank',
    code: '6210',
    country: 'Czechia',
  },
  {
    name: 'BNP Paribas S.A., pobočka Česká republika',
    shortName: 'BNP Paribas',
    code: '6300',
    country: 'Czechia',
  },
  {
    name: 'Partners Banka, a.s.',
    shortName: 'Partners',
    code: '6363',
    country: 'Czechia',
  },
  {
    name: 'Všeobecná úverová banka a.s., pobočka Praha',
    shortName: 'VÚB',
    code: '6700',
    country: 'Czechia',
  },
  {
    name: 'Sberbank CZ, a.s. v likvidaci',
    shortName: 'Sberbank',
    code: '6800',
    country: 'Czechia',
  },
  {
    name: 'Deutsche Bank Aktiengesellschaft Filiale Prag, organizační složka',
    shortName: 'Deutsche Bank',
    code: '7910',
    country: 'Czechia',
  },
  {
    name: 'Raiffeisen stavební spořitelna a.s.',
    shortName: 'Raiffeisen SS',
    code: '7950',
    country: 'Czechia',
  },
  {
    name: 'ČSOB Stavební spořitelna, a.s.',
    shortName: 'ČSOB SS',
    code: '7960',
    country: 'Czechia',
  },
  {
    name: 'MONETA Stavební Spořitelna, a.s.',
    shortName: 'MONETA SS',
    code: '7970',
    country: 'Czechia',
  },
  {
    name: 'Modrá pyramida stavební spořitelna, a.s.',
    shortName: 'Modrá pyramida',
    code: '7990',
    country: 'Czechia',
  },
  {
    name: 'Volksbank Raiffeisenbank Nordoberpfalz eG pobočka Cheb',
    shortName: 'Volksbank',
    code: '8030',
    country: 'Czechia',
  },
  {
    name: 'Oberbank AG pobočka Česká republika',
    shortName: 'Oberbank',
    code: '8040',
    country: 'Czechia',
  },
  {
    name: 'Stavební spořitelna České spořitelny, a.s.',
    shortName: 'SSČS',
    code: '8060',
    country: 'Czechia',
  },
  {
    name: 'Česká exportní banka, a.s.',
    shortName: 'ČEB',
    code: '8090',
    country: 'Czechia',
  },
  {
    name: 'HSBC Continental Europe, Czech Republic',
    shortName: 'HSBC',
    code: '8150',
    country: 'Czechia',
  },
  {
    name: 'Sparkasse Oberlausitz-Niederschlesien',
    shortName: 'Sparkasse',
    code: '8190',
    country: 'Czechia',
  },
  {
    name: 'FAS finance company s.r.o.',
    shortName: 'FAS',
    code: '8198',
    country: 'Czechia',
  },
  {
    name: 'Payment execution s.r.o.',
    shortName: 'Payment execution',
    code: '8220',
    country: 'Czechia',
  },
  {
    name: 'Bank of China (CEE) Ltd. Prague Branch',
    shortName: 'Bank of China',
    code: '8250',
    country: 'Czechia',
  },
  {
    name: 'Bank of Communications Co., Ltd., Prague Branch odštěpný závod',
    shortName: 'Bank of Communications',
    code: '8255',
    country: 'Czechia',
  },
  {
    name: 'Industrial and Commercial Bank of China Limited, Prague Branch, odštěpný závod',
    shortName: 'ICBC',
    code: '8265',
    country: 'Czechia',
  },
  {
    name: 'Multitude Bank p.l.c.',
    shortName: 'Multitude',
    code: '8500',
    country: 'Czechia',
  },
] as const satisfies readonly Bank[]

export default banks

export type BankCode = (typeof banks)[number]['code']
