import type { Currency } from '../types'

const currencies: Currency[] = [
  // 🔹 FIAT Currencies
  { code: 'CZK', symbol: 'Kč', symbolBefore: false, name: 'Czech Koruna', providers: ['CNB', 'currencyLayer', 'currencyCloud'] },
  { code: 'EUR', symbol: '€', symbolBefore: false, name: 'Euro', providers: ['currencyLayer', 'currencyCloud'] },
  { code: 'USD', symbol: '$', symbolBefore: true, name: 'United States Dollar', providers: ['currencyLayer', 'currencyCloud'] },
  { code: 'PLN', symbol: 'zł', symbolBefore: false, name: 'Polish Złoty', providers: ['currencyLayer', 'currencyCloud'] },
  { code: 'RON', symbol: 'lei', symbolBefore: false, name: 'Romanian Leu', providers: ['currencyLayer'] },
  { code: 'GBP', symbol: '£', symbolBefore: true, name: 'British Pound Sterling', providers: ['currencyLayer', 'currencyCloud'] },
  { code: 'RUB', symbol: '₽', symbolBefore: false, name: 'Russian Ruble', providers: ['currencyLayer'] },
  { code: 'HUF', symbol: 'Ft', symbolBefore: false, name: 'Hungarian Forint', providers: ['currencyLayer'] },
  { code: 'CHF', symbol: 'SFr.', symbolBefore: true, name: 'Swiss Franc', providers: ['currencyLayer'] },
  { code: 'DKK', symbol: 'kr', symbolBefore: false, name: 'Danish Krone', providers: ['currencyLayer'] },
  { code: 'SEK', symbol: 'kr', symbolBefore: false, name: 'Swedish Krona', providers: ['currencyLayer'] },
  { code: 'HRK', symbol: 'kn', symbolBefore: false, name: 'Croatian Kuna', providers: ['currencyLayer'] },
  { code: 'NOK', symbol: 'kr', symbolBefore: false, name: 'Norwegian Krone', providers: ['currencyLayer'] },
  { code: 'BGN', symbol: 'лв', symbolBefore: false, name: 'Bulgarian Lev', providers: ['currencyLayer'] },
  { code: 'TRY', symbol: '₺', symbolBefore: false, name: 'Turkish Lira', providers: ['currencyLayer'] },
  { code: 'AUD', symbol: '$', symbolBefore: true, name: 'Australian Dollar', providers: ['currencyLayer', 'currencyCloud'] },
  { code: 'CAD', symbol: '$', symbolBefore: true, name: 'Canadian Dollar', providers: ['currencyLayer', 'currencyCloud'] },
  { code: 'JPY', symbol: '¥', symbolBefore: true, name: 'Japanese Yen', providers: ['currencyLayer'] },
  { code: 'CNY', symbol: '¥', symbolBefore: true, name: 'Chinese Yuan', providers: ['currencyLayer'] },
  { code: 'INR', symbol: '₹', symbolBefore: true, name: 'Indian Rupee', providers: ['currencyLayer'] },
  { code: 'BRL', symbol: 'R$', symbolBefore: true, name: 'Brazilian Real', providers: ['currencyLayer'] },
  { code: 'MXN', symbol: '$', symbolBefore: true, name: 'Mexican Peso', providers: ['currencyLayer'] },
  { code: 'ZAR', symbol: 'R', symbolBefore: true, name: 'South African Rand', providers: ['currencyLayer'] },
  { code: 'SGD', symbol: '$', symbolBefore: true, name: 'Singapore Dollar', providers: ['currencyLayer'] },
  { code: 'HKD', symbol: '$', symbolBefore: true, name: 'Hong Kong Dollar', providers: ['currencyLayer'] },
  { code: 'KRW', symbol: '₩', symbolBefore: true, name: 'South Korean Won', providers: ['currencyLayer'] },
  { code: 'MYR', symbol: 'RM', symbolBefore: true, name: 'Malaysian Ringgit', providers: ['currencyLayer'] },
  { code: 'THB', symbol: '฿', symbolBefore: true, name: 'Thai Baht', providers: ['currencyLayer'] },
  { code: 'IDR', symbol: 'Rp', symbolBefore: true, name: 'Indonesian Rupiah', providers: ['currencyLayer'] },
  { code: 'PHP', symbol: '₱', symbolBefore: true, name: 'Philippine Peso', providers: ['currencyLayer'] },
  { code: 'AED', symbol: 'د.إ', symbolBefore: false, name: 'UAE Dirham', providers: ['currencyLayer'] },
  { code: 'SAR', symbol: '﷼', symbolBefore: false, name: 'Saudi Riyal', providers: ['currencyLayer'] },
  { code: 'ILS', symbol: '₪', symbolBefore: true, name: 'Israeli New Shekel', providers: ['currencyLayer'] },
  { code: 'EGP', symbol: '£', symbolBefore: true, name: 'Egyptian Pound', providers: ['currencyLayer'] },
  { code: 'NGN', symbol: '₦', symbolBefore: true, name: 'Nigerian Naira', providers: ['currencyLayer'] },
  { code: 'PKR', symbol: '₨', symbolBefore: true, name: 'Pakistani Rupee', providers: ['currencyLayer'] },
  { code: 'COP', symbol: '$', symbolBefore: true, name: 'Colombian Peso', providers: ['currencyLayer'] },
  { code: 'CLP', symbol: '$', symbolBefore: true, name: 'Chilean Peso', providers: ['currencyLayer'] },
  { code: 'PEN', symbol: 'S/', symbolBefore: true, name: 'Peruvian Sol', providers: ['currencyLayer'] },
  { code: 'VND', symbol: '₫', symbolBefore: false, name: 'Vietnamese Dong', providers: ['currencyLayer'] },
  { code: 'KZT', symbol: '₸', symbolBefore: false, name: 'Kazakhstani Tenge', providers: ['currencyLayer'] },
  { code: 'UAH', symbol: '₴', symbolBefore: false, name: 'Ukrainian Hryvnia', providers: ['currencyLayer'] },

  // 🔹 Crypto Currencies
  { code: 'BTC', symbol: '₿', symbolBefore: true, name: 'Bitcoin', providers: ['kraken', 'binance'] },
  { code: 'ETH', symbol: 'Ξ', symbolBefore: true, name: 'Ethereum', providers: ['kraken', 'binance'] },
  { code: 'ADA', symbol: '₳', symbolBefore: true, name: 'Cardano', providers: ['kraken', 'binance'] },
  { code: 'DOT', symbol: '◎', symbolBefore: true, name: 'Polkadot', providers: ['kraken', 'binance'] },
  { code: 'ATOM', symbol: '⚛', symbolBefore: true, name: 'Cosmos', providers: ['kraken', 'binance'] },
  { code: 'XRP', symbol: 'Ʀ', symbolBefore: true, name: 'Ripple', providers: ['kraken', 'binance'] },
  { code: 'LTC', symbol: 'Ł', symbolBefore: true, name: 'Litecoin', providers: ['kraken', 'binance'] },
  { code: 'SOL', symbol: '◎', symbolBefore: true, name: 'Solana', providers: ['kraken', 'binance'] },
  { code: 'DOGE', symbol: 'Ð', symbolBefore: true, name: 'Dogecoin', providers: ['kraken', 'binance'] },
  { code: 'MATIC', symbol: 'M', symbolBefore: true, name: 'Polygon', providers: ['kraken', 'binance'] },
  { code: 'AVAX', symbol: '⛰', symbolBefore: true, name: 'Avalanche', providers: ['kraken', 'binance'] },
]

export default currencies
