import type { CzNace } from '../types'

const czNace = [
  {
    code: '01',
    section: 'A',
    name: 'Rostlinná a živočišná výroba, myslivost a související činnosti',
  },
  { code: '02', section: 'A', name: 'Lesnictví a těžba dřeva' },
  { code: '03', section: 'A', name: 'Rybolov a akvakultura' },
  { code: '05', section: 'B', name: 'Těžba a úprava černého a hnědého uhlí' },
  { code: '06', section: 'B', name: 'Těžba ropy a zemního plynu' },
  { code: '07', section: 'B', name: 'Těžba a úprava rud' },
  { code: '08', section: 'B', name: 'Ostatní těžba a dobývání' },
  { code: '09', section: 'B', name: 'Podpůrné činnosti při těžbě' },
  { code: '10', section: 'C', name: 'Výroba potravinářských výrobků' },
  { code: '11', section: 'C', name: 'Výroba nápojů' },
  { code: '12', section: 'C', name: 'Výroba tabákových výrobků' },
  { code: '13', section: 'C', name: 'Výroba textilií' },
  { code: '14', section: 'C', name: 'Výroba oděvů' },
  { code: '15', section: 'C', name: 'Výroba usní a souvisejících výrobků' },
  {
    code: '16',
    section: 'C',
    name: 'Zpracování dřeva, výroba dřevěných, korkových, proutěných a slaměných výrobků, kromě nábytku',
  },
  { code: '17', section: 'C', name: 'Výroba papíru a výrobků z papíru' },
  { code: '18', section: 'C', name: 'Tisk a rozmnožování nahraných nosičů' },
  {
    code: '19',
    section: 'C',
    name: 'Výroba koksu a rafinovaných ropných produktů',
  },
  {
    code: '20',
    section: 'C',
    name: 'Výroba chemických látek a chemických přípravků',
  },
  {
    code: '21',
    section: 'C',
    name: 'Výroba základních farmaceutických výrobků a farmaceutických přípravků',
  },
  { code: '22', section: 'C', name: 'Výroba pryžových a plastových výrobků' },
  {
    code: '23',
    section: 'C',
    name: 'Výroba ostatních nekovových minerálních výrobků',
  },
  {
    code: '24',
    section: 'C',
    name: 'Výroba základních kovů, hutní zpracování kovů; slévárenství',
  },
  {
    code: '25',
    section: 'C',
    name: 'Výroba kovových konstrukcí a kovodělných výrobků, kromě strojů a zařízení',
  },
  {
    code: '26',
    section: 'C',
    name: 'Výroba počítačů, elektronických a optických přístrojů a zařízení',
  },
  { code: '27', section: 'C', name: 'Výroba elektrických zařízení' },
  { code: '28', section: 'C', name: 'Výroba strojů a zařízení j. n.' },
  {
    code: '29',
    section: 'C',
    name: 'Výroba motorových vozidel (kromě motocyklů), přívěsů a návěsů',
  },
  {
    code: '30',
    section: 'C',
    name: 'Výroba ostatních dopravních prostředků a zařízení',
  },
  { code: '31', section: 'C', name: 'Výroba nábytku' },
  { code: '32', section: 'C', name: 'Ostatní zpracovatelský průmysl' },
  { code: '33', section: 'C', name: 'Opravy a instalace strojů a zařízení' },
  {
    code: '35',
    section: 'D',
    name: 'Výroba a rozvod elektřiny, plynu, tepla a klimatizovaného vzduchu',
  },
  { code: '36', section: 'E', name: 'Shromažďování, úprava a rozvod vody' },
  { code: '37', section: 'E', name: 'Činnosti související s odpadními vodami' },
  {
    code: '38',
    section: 'E',
    name: 'Shromažďování, sběr a odstraňování odpadů, úprava odpadů k dalšímu využití',
  },
  {
    code: '39',
    section: 'E',
    name: 'Sanace a jiné činnosti související s odpady',
  },
  { code: '41', section: 'F', name: 'Výstavba budov' },
  { code: '42', section: 'F', name: 'Inženýrské stavitelství' },
  { code: '43', section: 'F', name: 'Specializované stavební činnosti' },
  {
    code: '45',
    section: 'G',
    name: 'Velkoobchod, maloobchod a opravy motorových vozidel',
  },
  { code: '46', section: 'G', name: 'Velkoobchod, kromě motorových vozidel' },
  { code: '47', section: 'G', name: 'Maloobchod, kromě motorových vozidel' },
  { code: '49', section: 'H', name: 'Pozemní a potrubní doprava' },
  { code: '50', section: 'H', name: 'Vodní doprava' },
  { code: '51', section: 'H', name: 'Letecká doprava' },
  {
    code: '52',
    section: 'H',
    name: 'Skladování a vedlejší činnosti v dopravě',
  },
  { code: '53', section: 'H', name: 'Poštovní a kurýrní činnosti' },
  { code: '55', section: 'I', name: 'Ubytování' },
  { code: '56', section: 'I', name: 'Stravování a pohostinství' },
  { code: '58', section: 'J', name: 'Vydavatelské činnosti' },
  {
    code: '59',
    section: 'J',
    name: 'Činnosti v oblasti filmů, videozáznamů a televizních programů, pořizování zvukových nahrávek a hudební vydavatelské činnosti',
  },
  { code: '60', section: 'J', name: 'Tvorba programů a vysílání' },
  { code: '61', section: 'J', name: 'Telekomunikační činnosti' },
  {
    code: '62',
    section: 'J',
    name: 'Činnosti v oblasti informačních technologií',
  },
  { code: '63', section: 'J', name: 'Informační činnosti' },
  {
    code: '64',
    section: 'K',
    name: 'Finanční zprostředkování, kromě pojišťovnictví a penzijního financování',
  },
  {
    code: '65',
    section: 'K',
    name: 'Pojištění, zajištění a penzijní financování, kromě povinného sociálního zabezpečení',
  },
  { code: '66', section: 'K', name: 'Ostatní finanční činnosti' },
  { code: '68', section: 'L', name: 'Činnosti v oblasti nemovitostí' },
  { code: '69', section: 'M', name: 'Právní a účetnické činnosti' },
  {
    code: '70',
    section: 'M',
    name: 'Činnosti vedení podniků; poradenství v oblasti řízení',
  },
  {
    code: '71',
    section: 'M',
    name: 'Architektonické a inženýrské činnosti; technické zkoušky a analýzy',
  },
  { code: '72', section: 'M', name: 'Výzkum a vývoj' },
  { code: '73', section: 'M', name: 'Reklama a průzkum trhu' },
  {
    code: '74',
    section: 'M',
    name: 'Ostatní profesní, vědecké a technické činnosti',
  },
  { code: '75', section: 'M', name: 'Veterinární činnosti' },
  {
    code: '77',
    section: 'N',
    name: 'Činnosti v oblasti pronájmu a operativního leasingu',
  },
  { code: '78', section: 'N', name: 'Činnosti související se zaměstnáním' },
  {
    code: '79',
    section: 'N',
    name: 'Činnosti cestovních agentur, kanceláří a jiné rezervační a související činnosti',
  },
  { code: '80', section: 'N', name: 'Bezpečnostní a pátrací činnosti' },
  {
    code: '81',
    section: 'N',
    name: 'Činnosti související se stavbami a úpravou krajiny',
  },
  {
    code: '82',
    section: 'N',
    name: 'Administrativní, kancelářské a jiné podpůrné činnosti pro podnikání',
  },
  {
    code: '84',
    section: 'O',
    name: 'Veřejná správa a obrana; povinné sociální zabezpečení',
  },
  { code: '85', section: 'P', name: 'Vzdělávání' },
  { code: '86', section: 'Q', name: 'Zdravotní péče' },
  { code: '87', section: 'Q', name: 'Pobytové služby sociální péče' },
  { code: '88', section: 'Q', name: 'Ambulantní nebo terénní sociální služby' },
  { code: '90', section: 'R', name: 'Tvůrčí, umělecké a zábavní činnosti' },
  {
    code: '91',
    section: 'R',
    name: 'Činnosti knihoven, archivů, muzeí a jiných kulturních zařízení',
  },
  {
    code: '92',
    section: 'R',
    name: 'Činnosti heren, kasin a sázkových kanceláří',
  },
  { code: '93', section: 'R', name: 'Sportovní, zábavní a rekreační činnosti' },
  {
    code: '94',
    section: 'S',
    name: 'Činnosti organizací sdružujících osoby za účelem prosazování společných zájmů',
  },
  {
    code: '95',
    section: 'S',
    name: 'Opravy počítačů a výrobků pro osobní potřebu a převážně pro domácnost',
  },
  { code: '96', section: 'S', name: 'Poskytování ostatních osobních služeb' },
  {
    code: '97',
    section: 'T',
    name: 'Činnosti domácností jako zaměstnavatelů domácího personálu',
  },
  {
    code: '98',
    section: 'T',
    name: 'Činnosti domácností produkujících blíže neurčené výrobky a služby pro vlastní potřebu',
  },
  {
    code: '99',
    section: 'U',
    name: 'Činnosti exteritoriálních organizací a orgánů',
  },
] as const satisfies readonly CzNace[]

export default czNace

export type CzNaceCode = (typeof czNace)[number]['code']
export type CzNaceSection = (typeof czNace)[number]['section']
