import type { Language } from '../types'

const languages: Language[] = [
  { code: 'en', name: 'English', native: 'English', cs: 'Angličtina' },
  { code: 'de', name: 'German', native: 'Deutsch', cs: 'Němčina' },
  { code: 'cs', name: 'Czech', native: 'Čeština', cs: 'Čeština' },
  { code: 'sk', name: 'Slovak', native: 'Slovenčina', cs: 'Slovenština' },
  { code: 'pl', name: 'Polish', native: 'Polski', cs: 'Polština' },
  { code: 'hr', name: 'Croatian', native: 'Hrvatski', cs: 'Chorvatština' },
  { code: 'ru', name: 'Russian', native: 'Русский', cs: 'Ruština' },
  { code: 'es', name: 'Spanish', native: 'Español', cs: 'Španělština' },
  { code: 'fr', name: 'French', native: 'Français', cs: 'Francouzština' },
  { code: 'it', name: 'Italian', native: 'Italiano', cs: 'Italština' },
  { code: 'nl', name: 'Dutch', native: 'Nederlands', cs: 'Holandština' },
  { code: 'ro', name: 'Romanian', native: 'Română', cs: 'Rumunština' },
  { code: 'ar', name: 'Arabic', native: 'العربية', cs: 'Arabština' },
  { code: 'sq', name: 'Albanian', native: 'Shqip', cs: 'Albánština' },
  { code: 'am', name: 'Amharic', native: 'አማርኛ', cs: 'Amharština' },
  { code: 'bs', name: 'Bosnian', native: 'Bosanski', cs: 'Bosenština' },
  { code: 'bg', name: 'Bulgarian', native: 'български', cs: 'Bulharština' },
  { code: 'ca', name: 'Catalan', native: 'Català', cs: 'Katalánština' },
  { code: 'da', name: 'Danish', native: 'Dansk', cs: 'Dánština' },
  { code: 'et', name: 'Estonian', native: 'Eesti', cs: 'Estonština' },
  { code: 'fi', name: 'Finnish', native: 'Suomi', cs: 'Finština' },
  { code: 'el', name: 'Greek', native: 'Ελληνικά', cs: 'Řečtina' },
  { code: 'ka', name: 'Georgian', native: 'ქართული', cs: 'Gruzínština' },
  { code: 'he', name: 'Hebrew', native: 'עברית', cs: 'Hebrejština' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', cs: 'Hindština' },
  { code: 'ig', name: 'Igbo', native: 'Asụsụ Igbo', cs: 'Igbo' },
  { code: 'ja', name: 'Japanese', native: '日本語', cs: 'Japonština' },
  { code: 'ku', name: 'Kurdish', native: 'Kurdî', cs: 'Kurdština' },
  { code: 'ko', name: 'Korean', native: '한국어', cs: 'Korejština' },
  { code: 'kk', name: 'Kazakh', native: 'қазақ тілі', cs: 'Kazachština' },
  { code: 'hu', name: 'Hungarian', native: 'Magyar', cs: 'Maďarština' },
  { code: 'mk', name: 'Macedonian', native: 'македонски', cs: 'Makedonština' },
  { code: 'lt', name: 'Lithuanian', native: 'lietuvių kalba', cs: 'Litevština' },
  { code: 'lv', name: 'Latvian', native: 'latviešu valoda', cs: 'Lotyšština' },
  { code: 'lb', name: 'Luxembourgish', native: 'Lëtzebuergesch', cs: 'Lucemburština' },
  { code: 'mn', name: 'Mongolian', native: 'Монгол хэл', cs: 'Mongolština' },
  { code: 'no', name: 'Norwegian', native: 'Norsk', cs: 'Norština' },
  { code: 'fa', name: 'Persian', native: 'فارسی', cs: 'Perština' },
  { code: 'pt', name: 'Portuguese', native: 'Português', cs: 'Portugalština' },
  { code: 'sl', name: 'Slovene', native: 'Slovenščina', cs: 'Slovinština' },
  { code: 'sr', name: 'Serbian', native: 'српски', cs: 'Srbština' },
  { code: 'sv', name: 'Swedish', native: 'Svenska', cs: 'Švédština' },
  { code: 'tr', name: 'Turkish', native: 'Türkçe', cs: 'Turečtina' },
  { code: 'uk', name: 'Ukrainian', native: 'Українська', cs: 'Ukrajinština' },
  { code: 'vi', name: 'Vietnamese', native: 'Tiếng Việt', cs: 'Vietnamština' },
  { code: 'zh', name: 'Chinese', native: '中文', cs: 'Čínština' },
  { code: 'af', name: 'Afrikaans', native: 'Afrikaans', cs: 'Afrikánština' },
  { code: 'hy', name: 'Armenian', native: 'Հայերեն', cs: 'Arménština' },
]

export default languages
